//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public area_admin()
        {
            this.are_population_record = new HashSet<are_population_record>();
            this.exam_record = new HashSet<exam_record>();
            this.group_admin = new HashSet<group_admin>();
        }
    
        public int id_area_admin { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> id_root_admin { get; set; }
        public string signature { get; set; }
        public string area_name { get; set; }
        public string user_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<are_population_record> are_population_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_record> exam_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_admin> group_admin { get; set; }
        public virtual root_admin root_admin { get; set; }
    }
}
