//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_record
    {
        public int idexam_record { get; set; }
        public Nullable<int> id_crimial { get; set; }
        public Nullable<int> id_rule { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<int> group_check_id { get; set; }
        public Nullable<int> area_check_id { get; set; }
        public Nullable<int> root_check_id { get; set; }
        public Nullable<int> score { get; set; }
        public string kind { get; set; }
        public string detail { get; set; }
    
        public virtual area_admin area_admin { get; set; }
        public virtual criminal criminal { get; set; }
        public virtual rule rule { get; set; }
        public virtual group_admin group_admin { get; set; }
        public virtual root_admin root_admin { get; set; }
    }
}
