//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public group_admin()
        {
            this.criminals = new HashSet<criminal>();
            this.exam_record = new HashSet<exam_record>();
        }
    
        public int id_group_admin { get; set; }
        public Nullable<int> group_id_in_area { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> id_area_admin { get; set; }
        public string signature { get; set; }
        public string user_number { get; set; }
    
        public virtual area_admin area_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criminal> criminals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_record> exam_record { get; set; }
    }
}
