//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prison_score
    {
        public int id_prison_score { get; set; }
        public Nullable<int> id_criminal { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string grade { get; set; }
        public Nullable<int> ed_fund_score { get; set; }
        public Nullable<int> ed_final_fund_score { get; set; }
        public Nullable<int> wk_fund_score { get; set; }
        public Nullable<int> wk_final_fund_score { get; set; }
        public Nullable<int> prison_scorecol { get; set; }
        public Nullable<int> absent_score { get; set; }
        public Nullable<int> month_score { get; set; }
        public Nullable<int> final_score { get; set; }
        public Nullable<int> sp_plus_score { get; set; }
        public Nullable<int> sp_minus_score { get; set; }
    
        public virtual criminal criminal { get; set; }
    }
}
