//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rule()
        {
            this.exam_record = new HashSet<exam_record>();
        }
    
        public int id_rule { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> num_id { get; set; }
        public string context { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_record> exam_record { get; set; }
    }
}
